In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('SMSSpamCollection', sep='\t', header=None)
dataset

0                                                  1
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
dataset.columns

Index([0, 1], dtype='int64')

# Changing the column name

In [4]:
dataset.rename(columns={0: 'result', 1: 'message'}, inplace=True)
dataset

result                                            message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
dataset['result'].value_counts()

result
ham     4825
spam     747
Name: count, dtype: int64

# Feature Extraction

In [6]:
import re
from sklearn.feature_extraction.text import CountVectorizer

X = dataset['message']
y = dataset['result']

In [7]:
def remove_punct(X):
    for i in range(0, len(X)):
        X[i] = re.sub('[^a-zA-Z]', ' ', X[i])
        X[i] = X[i].lower()
    return X

In [8]:
X = remove_punct(X)
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(X)

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [10]:
y = le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 0, 0])

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# Training the model

In [18]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [13]:
y_preds = model.predict(X_test)
y_preds

array([0, 1, 0, ..., 0, 0, 0])

# Checking Performance

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_preds)
print(cm)

[[1185   21]
 [   9  178]]


In [15]:
acc = accuracy_score(y_test, y_preds)
print(f'Accuracy: {acc}')

Accuracy: 0.9784637473079684


In [21]:
def predict(user_message, model, vectorizer):
    user_message = re.sub('^[a-zA-Z]', ' ', user_message)
    user_message = user_message.lower()
    user_message = [user_message]
    message = vectorizer.transform(user_message)
    pred = model.predict(message)
    if pred == 0:
        return "Ham"
    else:
        return"Spam"

In [22]:
user_message = input()
print(predict(user_message, model, vectorizer))

 fgr


Ham
